### ISSUE TITLE
Python 3.4 and theme location

### ISSUE THREAD

**Issue by rafspiny** [DaveMDS/egitu#10]
It seems that there is a packaging problem.
Here is what happens when running egitu with python 3.4
I use python-efl-9999 on gentoo.

```
 $ egitu
Traceback (most recent call last):
  File "/usr/bin/egitu", line 6, in <module>
    sys.exit(main())
  File "/usr/lib64/python3.4/site-packages/egitu/egitu.py", line 283, in main
    app = EgituApp(sys.argv[1:])
  File "/usr/lib64/python3.4/site-packages/egitu/egitu.py", line 48, in __init__
    self.win.populate()
  File "/usr/lib64/python3.4/site-packages/egitu/gui.py", line 510, in populate
    content=SafeIcon(self, 'git-branch'))
  File "/usr/lib64/python3.4/site-packages/egitu/utils.py", line 266, in __init__
    self.file = (theme_file_get(), 'elm/icon/%s/default' % icon_name)
  File "efl/elementary/image.pxi", line 124, in efl.elementary.__init__.Image.file.__set__ (efl/elementary/__init__.c:160089)
RuntimeError: Could not set file.
```

**Comment by DaveMDS** [comment]
Thanks for reporting!

commit c92699b5 should fix the issue,

please close this ticket if it's resolved for you

**Comment by rafspiny** [comment]
Seems good to me.
I actually applied your fix to eluminance as well. I hope it's ok.
