### ISSUE TITLE
need to add python-xdg in list of dependencies

### ISSUE THREAD

**Issue by mathieujobin** [DaveMDS/egitu#12]
Egitu will crash if you don't have `python-xdg` package installed

```
Traceback (most recent call last):
  File "/usr/local/bin/egitu", line 4, in <module>
    from egitu.egitu import main
  File "/usr/local/lib/python2.7/dist-packages/egitu/egitu.py", line 29, in <module>
    from egitu.utils import options, config_path, theme_file_get, KeyBindings
  File "/usr/local/lib/python2.7/dist-packages/egitu/utils.py", line 28, in <module>
    from xdg.BaseDirectory import xdg_config_home, xdg_cache_home
ImportError: No module named xdg.BaseDirectory
```

`sudo apt install python-xdg` solves it, but I think setup.py should report it

**Comment by DaveMDS** [comment]
Hi, 
xdg is already on setup.py and in requirements list in homepage. Simply distutils doesn't install dependency for you, this is how it work, nothing I can do atm, you need to install manually.

regards

**Comment by mathieujobin** [comment]
thanks
