### ISSUE TITLE
undefined symbol: eina_strbuf_replace_last

### ISSUE THREAD

**Issue by mathieujobin** [DaveMDS/egitu#13]
Running on *buntu 21.10

```
$ dpkg -l | egrep  '(eina|edje)'
ii  libeina-bin                                   1.25.1-1build1                              amd64        EFL optimized data types - extra tools
ii  libeina1a:amd64                               1.25.1-1build1                              amd64        EFL optimized data types

ii  libedje-bin                                   1.25.1-1build1                              amd64        EFL layout and animation tools - utilities
ii  libedje1:amd64                                1.25.1-1build1                              amd64        EFL layout and animation tools
$ pip list | grep efl
python-efl               1.25.0
```

```
$ /home/mathieu/.local/bin/egitu
Traceback (most recent call last):
  File "/home/mathieu/.local/bin/egitu", line 4, in <module>
    from egitu.egitu import main
  File "/home/mathieu/.local/lib/python3.9/site-packages/egitu/egitu.py", line 26, in <module>
    from efl import elementary as elm
ImportError: /lib/x86_64-linux-gnu/libedje.so.1: undefined symbol: eina_strbuf_replace_last
```

anything that I can do to run egitu again ?

Thanks

**Comment by DaveMDS** [comment]
Strange, I'm not getting this error on archlinux, but maybe I have an idea on whats the problem could be,.
Will try with ubuntu asap, please give me some days to test.

**Comment by DaveMDS** [comment]
I'm not able to reproduce your issue
What I have done:
 * installed ubuntu 21.10 in virtualbox
 * installed efl with: `sudo apt install libefl-all-dev`
 * `sudo apt install python3-dev python-dbus-dev`
 * installed python-efl from pip: `pip install python-efl`
 * installed egitu from git using: `sudo python3 setup install`

Egitu run without issue... do you see some relevant difference?

**Comment by mathieujobin** [comment]
I'm not too sure what's wrong with my system, I purged all efl* related packages.
and reinstalled with the same commands you provided. but I am still getting the same error. on setup this time.

```
mathieu:egitu :-) (master) $ sudo pip install python-efl
Collecting python-efl
  Downloading python-efl-1.25.0.tar.gz (11.7 MB)
     |████████████████████████████████| 11.7 MB 8.2 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: python-efl
  Building wheel for python-efl (PEP 517) ... done
  Created wheel for python-efl: filename=python_efl-1.25.0-cp39-cp39-linux_x86_64.whl size=11466191 sha256=0f31bdf5ff085a8c3fde6b624e040cf34d004315ecd5c25fb2a42a652bb35a16
  Stored in directory: /root/.cache/pip/wheels/92/3b/fc/8e83e548c26d4eda344e296d69c7e0b3244de92e036e7552b5
Successfully built python-efl
Installing collected packages: python-efl
Successfully installed python-efl-1.25.0
mathieu:egitu :-) (master) $ sudo python setup.py install
running install
running build
running build_edc
compiling theme "default" from edc file: "data/themes/default/main.edc"
edje_cc -v -id data/themes/default -id data/themes/default/images -fd data/themes/default -fd data/themes/default/fonts -sd data/themes/default -sd data/themes/default/sounds data/themes/default/main.edc build/themes/default.edj
/usr/bin/edje_cc: symbol lookup error: /lib/x86_64-linux-gnu/libedje.so.1: undefined symbol: eina_strbuf_replace_last
error: command '/usr/bin/edje_cc' failed with exit code 127
mathieu:egitu :-( 1 (master) $ ls -l /lib/x86_64-linux-gnu/libedje.so.1
lrwxrwxrwx 1 root root 17 Mar  5  2021 /lib/x86_64-linux-gnu/libedje.so.1 -> libedje.so.1.25.1
mathieu:egitu :-) (master) $ ls -l /lib/x86_64-linux-gnu/libedje.so.1.25.1 
-rw-r--r-- 1 root root 1119392 Mar  5  2021 /lib/x86_64-linux-gnu/libedje.so.1.25.1
mathieu:egitu :-) (master) $
```

**Comment by mathieujobin** [comment]
wait, why does it look up files in `/lib/` and not `/usr/lib` ...

**Comment by mathieujobin** [comment]
got it, I had one file left over in `/usr/local` from an old install from source

moved it away, ran `ldconfig -v` again to be sure and I got it to install and run ! thank you

**Comment by mathieujobin** [comment]
Just so you know, since we resolved this issue, I am using egitu daily ! 

Thank you
