### ISSUE TITLE
egitu crash on start-up

### ISSUE THREAD

**Issue by seoz** [DaveMDS/egitu#4]
[Prerequisite]
- python 2.7
- using up-to-date python-efl binding

[Backtrace]
$ egitu .
Traceback (most recent call last):
  File "/usr/local/bin/egitu", line 4, in <module>
    from egitu.egitu import main
  File "/usr/local/lib/python2.7/dist-packages/egitu/egitu.py", line 28, in <module>
    from efl.elementary.entry import utf8_to_markup
  File "efl/elementary/entry.pyx", line 1, in init efl.elementary.entry (efl/elementary/entry.c:23866)
  File "efl/elementary/layout_class.pyx", line 1, in init efl.elementary.layout_class (efl/elementary/layout_class.c:10969)
  File "efl/elementary/object.pyx", line 1984, in init efl.elementary.object (efl/elementary/object.c:24886)
  File "efl/eo/efl.eo.pyx", line 102, in efl.eo._object_mapping_register (efl/eo/efl.eo.c:1459)
ValueError: Object type name 'Elm_Widget' already registered.

**Comment by DaveMDS** [comment]
All your python-efl stuff are broken, you have some old python-efl files installed around, 
uninstall/reinstall python-efl to fix this error
