### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by simotek** [DaveMDS/egitu#7]
`/home/simon` is obviously my home directory and not a git repo, why it decided to load that at startup i'm not sure, but egitu is failing to load because of this.

`Trying to load a repo from: /home/simon
ERROR: Cannot find a repo at: "/home/simon"
Traceback (most recent call last):
  File "/usr/bin/egitu", line 6, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/egitu/egitu.py", line 283, in main
    app = EgituApp(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/egitu/egitu.py", line 67, in __init__
    RepoSelector(self)
  File "/usr/lib/python2.7/site-packages/egitu/gui.py", line 65, in __init__
    self.part_content_set('title,icon', Icon(self, standard='egitu'))
  File "efl/elementary/icon.pxi", line 38, in efl.elementary.__init__.Icon.__init__ (efl/elementary/__init__.c:154226)
  File "efl/evas/efl.evas_object.pxi", line 209, in efl.evas.Object._set_properties_from_keyword_args (efl/evas/efl.evas.c:51771)
  File "efl/eo/efl.eo.pyx", line 273, in efl.eo.Eo._set_properties_from_keyword_args (efl/eo/efl.eo.c:3311)
  File "efl/elementary/icon.pxi", line 109, in efl.elementary.__init__.Icon.standard.__set__ (efl/elementary/__init__.c:154823)
`

**Comment by NuLogicSystems** [comment]
I can confirm this issue:
 egitu
Traceback (most recent call last):
  File "/usr/bin/egitu", line 6, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/egitu/egitu.py", line 283, in main
    app = EgituApp(sys.argv[1:])
  File "/usr/lib/python3.5/site-packages/egitu/egitu.py", line 48, in __init__
    self.win.populate()
  File "/usr/lib/python3.5/site-packages/egitu/gui.py", line 492, in populate
    bt = MainMenuButton(self.app)
  File "/usr/lib/python3.5/site-packages/egitu/gui.py", line 283, in __init__
    content=Icon(app.win, standard='home'))
  File "efl/elementary/icon.pxi", line 38, in efl.elementary.__init__.Icon.__init__ (efl/elementary/__init__.c:156140)
  File "efl.evas_object.pxi", line 209, in efl.evas.Object._set_properties_from_keyword_args (efl/evas/efl.evas.c:51748)
  File "efl.eo.pyx", line 276, in efl.eo.Eo._set_properties_from_keyword_args (efl/eo/efl.eo.c:3446)
  File "efl/elementary/icon.pxi", line 109, in efl.elementary.__init__.Icon.standard.__set__ (efl/elementary/__init__.c:156737)
RuntimeWarning: Setting standard icon failed

**Comment by DaveMDS** [comment]
egitu is not finding the "egitu" icon, thus failing.

I do not get this error here, I'm closing the bug, please reopen if this still occur
