### ISSUE TITLE
Egitu will not start.

### ISSUE THREAD

**Issue by NuLogicSystems** [DaveMDS/egitu#9]
Failing to run on EFL 1.18 & pyton-efl from git.
$ egitu
Traceback (most recent call last):
  File "/usr/bin/egitu", line 6, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/egitu/egitu.py", line 283, in main
    app = EgituApp(sys.argv[1:])
  File "/usr/lib/python3.5/site-packages/egitu/egitu.py", line 48, in **init**
    self.win.populate()
  File "/usr/lib/python3.5/site-packages/egitu/gui.py", line 492, in populate
    bt = MainMenuButton(self.app)
  File "/usr/lib/python3.5/site-packages/egitu/gui.py", line 283, in **init**
    content=Icon(app.win, standard='home'))
  File "efl/elementary/icon.pxi", line 38, in efl.elementary.**init**.Icon.**init** (efl/elementary/**init**.c:156140)
  File "efl.evas_object.pxi", line 209, in efl.evas.Object._set_properties_from_keyword_args (efl/evas/efl.evas.c:51748)
  File "efl.eo.pyx", line 276, in efl.eo.Eo._set_properties_from_keyword_args (efl/eo/efl.eo.c:3446)
  File "efl/elementary/icon.pxi", line 109, in efl.elementary.__init__.Icon.standard.**set** (efl/elementary/**init**.c:156737)
RuntimeWarning: Setting standard icon failed

**Comment by DaveMDS** [comment]
Arggh, this one is way much problematic than the epack one
...I'm working on this, but probably will need some fix in efl itself :(

In the meantime I think I have a workaround for you:
`elementary_config` -> `Icons` -> Check `Use elementary icons`

they are the same icons as the Enlightenment-X theme, but are included directly
in the elm theme and thus they should fallback gracefully to the old names
used by egitu.

And btw, if you want to use the bluish efl icons you should always use that
checkbox in elm_config. They are LOTS faster to load. Enlightenemnt-X has
been done only for non-efl apps.

PLease let me know if this workaround works for you

**Comment by NuLogicSystems** [comment]
Yes!! That did the trick, thank you so much.
I do love this application, it has come in very handy.. :)
